### ISSUE TITLE
Add support for `Date`

### ISSUE THREAD

**Issue by adamazad** [graphprotocol/graph-ts#188]
I need to `Date` object for a function that doesn't need to depend on `event.block.timestamp`

**Comment by leoyvens** [comment]
Could you please elaborate on your use case?

**Comment by adamazad** [comment]
Suppose I have an entity like this.

```typescript
type FixedPriceSaleUser implements EntityMetadata @entity {
  id: ID!
  createdAt: Int!
  updatedAt: Int!
  deletedAt: Int
}
```

This entity is created via a helper function:

```typescript
export function createOrGetFixedPriceSaleUser(
  saleAddress: Address,
  userAddres: Address,
  timestamp: BigInt //  pass event.block.timestamp
): FixedPriceSaleUser {
  let fixedPriceSaleUserId = createFixedPriceSaleUserId(saleAddress, userAddres) // <contract-address>/users/<user-address>

  // First, fetch or register the new user
  let fixedPriceSaleUser = FixedPriceSaleUser.load(fixedPriceSaleUserId)

  if (fixedPriceSaleUser == null) {
    fixedPriceSaleUser = new FixedPriceSaleUser(fixedPriceSaleUserId)
    fixedPriceSaleUser.createdAt = timestamp
    fixedPriceSaleUser.updatedAt = timestamp
    fixedPriceSaleUser.save()
  }

  return fixedPriceSaleUser as FixedPriceSaleUser
}
```


To call `createOrGetFixedPriceSaleUser`, the third parameter has to be `event.block.timestamp`. I wish to remove this dependency; drop the third argument in favor of `Date.now()`

**Comment by schmidsi** [comment]
Hmm, indexing has to be deterministic: If two indexers index the same subgraph, both should have the exact same data in their database. Introducing a `Date.now()` function would break that paradigm. Why not just pass `event.block.timestamp`?

I'm closing this, since we won't add support `Date.now()` due to the reasons above. Feel free to still reply if you have any more comments or a use-case that we did not think about yet.
