### ISSUE TITLE
HTTP requests

### ISSUE THREAD

**Issue by GV14982** [graphprotocol/graph-ts#244]
Hey all, this might be a dumb question,

But is there a way to make HTTP requests from within the WASM that runs in the graph node? I found a [library](https://github.com/JairusSW/as-http) for AssemblyScript, but I am having troubles with it and I want to make sure I am not wasting my time trying to get it working.

It seems like that library bootstraps the HTTP client from the runtime that the WASM is being run in.

Just let me know if I'm way off base here or if this might be possible. Thanks!

**Comment by maoueh** [comment]
It's not possible to run HTTP queries via the `graph-node`. This is because WASM, which AssemblyScript compiles to, is a sandboxed environment which means we must explicitly gives some primitives to make such HTTP call and it's not the case today.

The only thing that does HTTP call and is supported is accessing contract's state (https://thegraph.com/docs/en/developer/assemblyscript-api/#access-to-smart-contract-state). Those actually performs an HTTP call under the cover but the primitives to perform any HTTP calls is not exposed to you.

What is your use case, maybe there is some alternatives that we could suggest?

**Comment by GV14982** [comment]
Hey @maoueh, thanks so much for the response.

The use case is that the token metadata I have is stored on a server that you can access via HTTP, and I want to cache that JSON data along with the rest of the token information in the subgraph.

Could you point me in the right direction of where the HTTP request for accessing the smart contract state is? I might be interested in submitting a PR adding this functionality.

**Comment by maoueh** [comment]
> Could you point me in the right direction of where the HTTP request for accessing the smart contract state is? I might be interested in submitting a PR adding this functionality.

Performing an HTTP call has negative impact on the performance of the subgraph, from our experience, those are usually used too often leading to severe slowness in the syncing time Moreover, HTTP poses challenges with proof of indexing required for proper decentralization of The Graph. We would not accept such feature, at least in the current form of a facility to perform free form HTTP request.

Your best option is to bridge the gap at query time directly, adding caching where it makes sense (user's browser, server disk, etc.).

We are looking into alternatives ways that would enable data sources from an HTTP stream of some sort. Nothing that is ready, but something we have in mind.

**Comment by GV14982** [comment]
Ah I see, I will just need to write a custom caching solution then. Thanks, feel free to close this.
