### ISSUE TITLE
Support for `Date.now()` function 

### ISSUE THREAD

**Issue by abskmj** [graphprotocol/graph-ts#269]
I'm implementing a subgraph to index transaction data of an exchange not older than 30 days. I want to programmatically skip older events using the `Date.now()` function. The start block will not help as the pairs-created events need to be indexed from data older than 30 days.

**Comment by evaporei** [comment]
Hey @abskmj even though `Date.now()` is a very useful function, unfortunately we can't add it to the subgraph API because of determinism issues.

Every subgraph should have deterministic indexing, the only source of entropy is a blockchain, which preserves this characteristic.

This isn't possible with functions such as `Math.random()` and `Date.now()` which return different values for each call, breaking the subgraph's deterministic source of entropy.

**Comment by franz101** [comment]
Any way to use the block number and a time oracle?

**Comment by schmidsi** [comment]
@abskmj you can use `block.timestamp` as described here for your use case: https://thegraph.com/docs/en/developer/assemblyscript-api/#events-and-block-transaction-data
