### ISSUE TITLE
Don't require mappings to export `allocate_memory`

### ISSUE THREAD

**Issue by Jannis** [graphprotocol/graph-ts#7]
Right now, developers have to put
```js
import 'allocator/arena'
export { allocate_memory }
```
a the top of their mapping files. This is not obvious and also not even valid TypeScript (`allocate_memory` appears to be undefined).

Ideally, we would take care of exporting this for developers.

Of the top of my head, I see two ways to achieve this:

1. Add an AssemblyScript transform script and pass it to `asc.main` in Graph CLI. This transform script would update the mapping AST to add the two statements above.
2. Add the two lines above to the mappings before we compile them.

Number 1 seems to be the cleaner solution.

**Comment by leodasvacas** [comment]
This seems a bit against the spirit of explicit imports, but seems ok since it's just this (and soon reset_memory). Deserves priority both for the DX value and also because it'd be good to have this before upgrading AssemblyScript and before we start freeing memory between mapping calls, two changes that would alter this export.

**Comment by leodasvacas** [comment]
Actually, this should be imported from graph-ts rather than directly from assemblyscript with `import allocate_memory from '@graphprotocol/graph-ts'`

**Comment by Jannis** [comment]
Subgraph authors shouldn't have to deal with this at all. Having to import and export it again manually only adds hassle, it adds no value, and is easy to forget. So I still think it should be added using an AST transform script that we pass to `asc.main()`.

**Comment by leodasvacas** [comment]
I agree, I was just noting that if assemblyscript renames this it's ok because we re-export it from graph-ts.

**Comment by leodasvacas** [comment]
Another suggestion for how to implement this: Have a `globals/globals.ts` in this repository where we put this and anything else that should go in the global namespace and additionally pass `node_modules/graph-ts/globals` to `--libs` when compiling with `asc`.

**Comment by leodasvacas** [comment]
That approach didn't work for a few reasons:
- It caused a name conflict with the original `allocate_memory`, but that could be worked around by giving it a different name.
- The export was put in the global namespace for the mapping but not exported to the host.
- When I tried exporting it, it couldn't be called because it was a considered a global and not a function.

Perhaps we can still have a `global.ts` and append it to each mapping?

**Comment by Jannis** [comment]
That's an idea — kinda hacky but might be ok.
